-- Entrio POS PostgreSQL Schema v5 (Tam Revizyon + Hızlı Notlar)
-- Supabase SQL Editor'de çalıştırılmalıdır.
-- Önemli: Tüm tablolar DROP edilerek yeniden oluşturulur (temiz başlangıç).

-- ─── Bağımlılık sırasına göre temizlik ─────────────────────────────────────
DROP TABLE IF EXISTS public.quick_notes CASCADE;
DROP TABLE IF EXISTS public.supplier_transactions CASCADE;
DROP TABLE IF EXISTS public.customer_transactions CASCADE;
DROP TABLE IF EXISTS public.cash_transactions CASCADE;
DROP TABLE IF EXISTS public.cash_registers CASCADE;
DROP TABLE IF EXISTS public.purchase_items CASCADE;
DROP TABLE IF EXISTS public.purchases CASCADE;
DROP TABLE IF EXISTS public.sale_items CASCADE;
DROP TABLE IF EXISTS public.sales CASCADE;
DROP TABLE IF EXISTS public.stock_movements CASCADE;
DROP TABLE IF EXISTS public.products CASCADE;
DROP TABLE IF EXISTS public.customers CASCADE;
DROP TABLE IF EXISTS public.suppliers CASCADE;
DROP TABLE IF EXISTS public.categories CASCADE;
DROP TABLE IF EXISTS public.settings CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;
DROP TABLE IF EXISTS public.branches CASCADE;

-- ─── Tablolar ────────────────────────────────────────────────────────────────

CREATE TABLE public.branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    is_active BOOLEAN DEFAULT true
);

CREATE TABLE public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    full_name TEXT NOT NULL,
    role TEXT NOT NULL,
    branch_id BIGINT REFERENCES public.branches(id),
    is_active BOOLEAN DEFAULT true
);

CREATE TABLE public.settings (
    key TEXT PRIMARY KEY,
    value JSONB NOT NULL
);

-- Yeni Eklenen: Hızlı Notlar Tablosu (Local Storage Yerine Bulut)
CREATE TABLE public.quick_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL,
    created_at BIGINT DEFAULT (EXTRACT(EPOCH FROM NOW()) * 1000),
    updated_at BIGINT DEFAULT (EXTRACT(EPOCH FROM NOW()) * 1000)
);

CREATE TABLE public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    parent_id BIGINT REFERENCES public.categories(id),
    color TEXT,
    icon TEXT
);

CREATE TABLE public.suppliers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT,
    email TEXT,
    tax_number TEXT,
    balance DECIMAL(15,2) DEFAULT 0,
    is_active BOOLEAN DEFAULT true
);

CREATE TABLE public.customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT,
    email TEXT,
    balance DECIMAL(15,2) DEFAULT 0,
    customer_type TEXT DEFAULT 'retail',
    is_active BOOLEAN DEFAULT true
);

CREATE TABLE public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barcode TEXT UNIQUE,
    name TEXT NOT NULL,
    category_id BIGINT REFERENCES public.categories(id),
    supplier_id BIGINT REFERENCES public.suppliers(id),
    sale_price DECIMAL(15,2) NOT NULL,
    purchase_price DECIMAL(15,2) NOT NULL,
    stock_quantity DECIMAL(15,2) DEFAULT 0,
    min_stock_level DECIMAL(15,2) DEFAULT 0,
    track_stock BOOLEAN DEFAULT true,
    tax_rate DECIMAL(5,2) DEFAULT 0,
    unit TEXT DEFAULT 'adet',
    is_active BOOLEAN DEFAULT true
);

CREATE TABLE public.stock_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.products(id),
    movement_type TEXT NOT NULL,
    quantity DECIMAL(15,2) NOT NULL,
    unit_price DECIMAL(15,2),
    item_discount DECIMAL(15,2),
    reference_id BIGINT,           
    reference TEXT,                
    notes TEXT,
    created_at BIGINT DEFAULT (EXTRACT(EPOCH FROM NOW()) * 1000)
);

CREATE TABLE public.sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_number TEXT UNIQUE,
    customer_id BIGINT REFERENCES public.customers(id),
    subtotal DECIMAL(15,2),        
    total_amount DECIMAL(15,2) NOT NULL,
    paid_amount DECIMAL(15,2) DEFAULT 0,
    discount_amount DECIMAL(15,2) DEFAULT 0,
    discount_type TEXT,
    discount_value DECIMAL(15,2) DEFAULT 0,
    discount_reason TEXT,
    payment_method TEXT,
    split_payments JSONB,
    status TEXT DEFAULT 'completed',
    original_sale_id BIGINT REFERENCES public.sales(id),
    notes TEXT,
    created_at BIGINT DEFAULT (EXTRACT(EPOCH FROM NOW()) * 1000)
);

CREATE TABLE public.sale_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT REFERENCES public.sales(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id),
    name TEXT,
    quantity DECIMAL(15,2) NOT NULL,
    unit_price DECIMAL(15,2) NOT NULL,
    line_total DECIMAL(15,2) NOT NULL,
    discount DECIMAL(15,2) DEFAULT 0,
    kdv_amount DECIMAL(15,2) DEFAULT 0
);

CREATE TABLE public.purchases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_number TEXT,
    invoice_number TEXT,
    invoice_title TEXT,
    invoice_date DATE,
    due_date DATE,
    supplier_id BIGINT REFERENCES public.suppliers(id),
    supplier_name TEXT,
    subtotal DECIMAL(15,2),
    total_amount DECIMAL(15,2) NOT NULL,
    paid_amount DECIMAL(15,2) DEFAULT 0,
    status TEXT DEFAULT 'completed',
    payment_method TEXT,
    discount_amount DECIMAL(15,2) DEFAULT 0,
    kdv_amount DECIMAL(15,2) DEFAULT 0,
    otv_amount DECIMAL(15,2) DEFAULT 0,
    waybill_number TEXT,
    waybill_date DATE,
    notes TEXT,
    siparis_no TEXT,
    siparis_date DATE,
    category_id BIGINT REFERENCES public.categories(id),
    created_at BIGINT DEFAULT (EXTRACT(EPOCH FROM NOW()) * 1000)
);

CREATE TABLE public.purchase_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_id BIGINT REFERENCES public.purchases(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id),
    name TEXT,
    quantity DECIMAL(15,2) NOT NULL,
    unit_price DECIMAL(15,2) NOT NULL,
    unit TEXT DEFAULT 'adet',
    line_total DECIMAL(15,2) NOT NULL,
    kdv_rate DECIMAL(5,2) DEFAULT 0,
    otv_rate DECIMAL(5,2) DEFAULT 0,
    discount_percent DECIMAL(5,2) DEFAULT 0,
    discount_amount DECIMAL(15,2) DEFAULT 0,
    kdv_amount DECIMAL(15,2) DEFAULT 0,
    otv_amount DECIMAL(15,2) DEFAULT 0
);

CREATE TABLE public.cash_registers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    is_default_for TEXT,
    is_active BOOLEAN DEFAULT true,
    current_balance DECIMAL(15,2) DEFAULT 0,
    general_balance DECIMAL(15,2) DEFAULT 0,
    last_day_close_date DATE,
    last_day_close_at BIGINT,
    credit_limit DECIMAL(15,2),
    billing_day INT,
    due_day INT
);

CREATE TABLE public.cash_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    register_id BIGINT REFERENCES public.cash_registers(id),
    transaction_type TEXT NOT NULL,
    amount DECIMAL(15,2) NOT NULL,
    balance_after DECIMAL(15,2),
    gen_bal_impact DECIMAL(15,2),
    is_day_close BOOLEAN DEFAULT false,
    is_consolidated BOOLEAN DEFAULT false,
    day_close_data JSONB,
    purchase_id BIGINT,
    reference_id BIGINT,
    reference TEXT,
    notes TEXT,
    created_at BIGINT DEFAULT (EXTRACT(EPOCH FROM NOW()) * 1000)
);

CREATE TABLE public.customer_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT REFERENCES public.customers(id),
    transaction_type TEXT NOT NULL,
    amount DECIMAL(15,2) NOT NULL,
    balance_after DECIMAL(15,2) NOT NULL,
    payment_method TEXT,
    transaction_date DATE,
    reference_id BIGINT,
    sale_number TEXT,
    notes TEXT,
    created_at BIGINT DEFAULT (EXTRACT(EPOCH FROM NOW()) * 1000)
);

CREATE TABLE public.supplier_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT REFERENCES public.suppliers(id),
    transaction_type TEXT NOT NULL,
    amount DECIMAL(15,2) NOT NULL,
    balance_after DECIMAL(15,2),
    payment_method TEXT,
    transaction_date DATE,
    reference_id BIGINT,
    notes TEXT,
    invoice_number TEXT,
    invoice_title TEXT,
    created_at BIGINT DEFAULT (EXTRACT(EPOCH FROM NOW()) * 1000)
);

-- ─── RLS Devre Dışı ────────────────────────────────────────────────────────
ALTER TABLE public.branches DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.quick_notes DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.suppliers DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.products DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_movements DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.sale_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchases DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchase_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.cash_registers DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.cash_transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.supplier_transactions DISABLE ROW LEVEL SECURITY;

-- ─── Seed Data ─────────────────────────────────────────────────────────────

INSERT INTO public.branches (name, is_active) VALUES ('Merkez Şube', true);

INSERT INTO public.customers (name, customer_type, balance, is_active)
VALUES ('Perakende Müşteri', 'retail', 0, true);

INSERT INTO public.cash_registers (name, type, is_default_for, current_balance, general_balance, last_day_close_date, is_active)
VALUES
('Nakit Kasa', 'cash', 'cash', 0, 0, CURRENT_DATE, true),
('POS Hesabı 1', 'pos', 'card', 0, 0, CURRENT_DATE, true),
('Banka Hesabı 1', 'bank', 'transfer', 0, 0, CURRENT_DATE, true);

INSERT INTO public.categories (name, color, icon)
VALUES
('Genel', '#65c43d', 'tag'),
('Gıda', '#22c55e', 'shopping-bag'),
('Elektronik', '#3b82f6', 'cpu'),
('Giyim', '#f59e0b', 'shirt');

-- Local Storage'daki ilk not örneği (opsiyonel)
INSERT INTO public.quick_notes (content) VALUES ('İlk hızlı notunuz...');

INSERT INTO public.users (email, password, full_name, role, branch_id, is_active)
VALUES
('admin@pos.com', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', 'Hesap Yöneticisi', 'admin', 1, true),
('kasiyer@pos.com', 'b14361404c078ffd549c03db604f0ad8fb50ddf898a4b80eb7f45a5fa7c8b4b5', 'Kasiyer', 'cashier', 1, true);

INSERT INTO public.settings (key, value)
VALUES
('company_info', '{"name": "Entrio Perakende", "address": "Merkez Mah. Atatürk Cad. No:1", "phone": "0850 123 45 67", "logo": null}'),
('receipt_template', '"template_1"');
